# Generated by Django 4.2.2 on 2023-06-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_reviews_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=0, upload_to='covers/'),
            preserve_default=False,
        ),
    ]
